# Generated by Django 5.2.15 on 2026-07-05 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="utworzono"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="zmodyfikowano"),
                ),
                (
                    "case_id",
                    models.CharField(
                        help_text="Np. I C 123/24 — odpowiednik --case-id z wersji CLI.",
                        max_length=120,
                        unique=True,
                        verbose_name="sygnatura / identyfikator sprawy",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="opis")),
                (
                    "persons_cache",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Mapa: znormalizowana osoba → inicjały (jak persons_cache.json).",
                        verbose_name="cache osób",
                    ),
                ),
            ],
            options={
                "verbose_name": "sprawa",
                "verbose_name_plural": "sprawy",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="utworzono"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="zmodyfikowano"),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="nazwa oryginalna"),
                ),
                (
                    "source_file",
                    models.FileField(
                        upload_to="dokumenty/zrodlowe/%Y/%m/",
                        verbose_name="plik źródłowy",
                    ),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        upload_to="dokumenty/wyniki/%Y/%m/",
                        verbose_name="plik wynikowy",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje"),
                            ("processing", "Przetwarzanie"),
                            ("done", "Gotowy"),
                            ("failed", "Błąd"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="komunikat błędu"),
                ),
                (
                    "entity_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="wykryte encje"
                    ),
                ),
                (
                    "person_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="wykryte osoby"
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True, null=True, verbose_name="czas przetwarzania [s]"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="zakończono"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="dokumenty.case",
                        verbose_name="sprawa",
                    ),
                ),
            ],
            options={
                "verbose_name": "dokument",
                "verbose_name_plural": "dokumenty",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="dokumenty_d_status_1613de_idx"
                    )
                ],
            },
        ),
    ]
