# Generated by Django 5.2.15 on 2026-07-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dokumenty", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="cancel_requested",
            field=models.BooleanField(
                default=False, verbose_name="zażądano zatrzymania"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="task_id",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="id zadania kolejki"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Oczekuje"),
                    ("processing", "Przetwarzanie"),
                    ("done", "Gotowy"),
                    ("failed", "Błąd"),
                    ("cancelled", "Anulowany"),
                ],
                default="pending",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
